### PR TITLE
resolved express pymatgen/numpy errors with python versions => 3.7

### PR DESCRIPTION
**Pull request by adewyer**

### CODE REVIEW

**Review by csadorf — COMMENTED** [review]
We might want to consider to just use one numpy version across all supported Python versions, i.e., generally pin it to `1.19.5`. Otherwise there is risk that the software behaves slightly differently across different Python versions.

**Comment by adewyer** [comment]
@csadorf thank you for that heads up. I think this will likely be something that needs to be decided by @triplepoint, as to what the best solution is, as different numpy versions are compatible with differing python versions. i.e. numpy 1.20.1 works for python 3.7 but not python 3.6. This also may become an issue with other packages as well as python/package codes update.

**Comment by csadorf** [comment]
> @csadorf thank you for that heads up. I think this will likely be something that needs to be decided by @triplepoint, as to what the best solution is, as different numpy versions are compatible with differing python versions. i.e. numpy 1.20.1 works for python 3.7 but not python 3.6. This also may become an issue with other packages as well as python/package codes update.

@adewyer True. To alleviate this problem, I recommend that the Exabyte stack adopts a support table related to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html). This would make it easier to have high compatibility with the rest of the Python and NumPy/SciPy ecosystem. At the moment [there is no numpy version that is still maintained and that still supports Python 3.6](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule). Python 3.6 in itself is [only receiving security updates](https://www.python.org/dev/peps/pep-0494/#lifespan) and will reach [EOL very soon](https://endoflife.date/python).

**Review by triplepoint — APPROVED** [review]
cat_lgtm

**Comment by triplepoint** [comment]
@csadorf The issue we were running into here was that numpy 1.19 fails on python 3.7+ on linux, for some of the nwchem related work, but numpy 1.20 dropped python 3.6 support, so we can't use it there, and python 3.6 support is still a requirement.

Interestingly, numpy 1.19 didn't exhibit the same errors on python 3.6, or on python 3.7+ on macos.  I'm starting to suspect a badly-compiled 1.19 manylinux binary wheel, since the pre-built binaries are OS specific.

It could be that building numpy from source at version 1.19.x would work fine in all cases, but I'd rather avoid that.  And in any case, python 3.6 only has 10 more months of life left, after which we'll have a good case for dropping support ourselves and encouraging everyone move to 3.7+.

I do very much like the idea of following something like the NEP 29 link you posted.  In general, we should be consistent and public with the versions of all the packages we pre-install, and also communicate our policy and plan for upgrading and deprecating those versions over time.  It's something we'll look into.

**Review by timurbazhirov — APPROVED** [review]

**Pull request merged**
